[workspace]
resolver = "2"

members = [
    "programs/*",
    "program-tests/*",
    # "sdks/arch-token-metadata-rs", # JS/TS: sdks/arch-token-metadata-js
    # "examples/create-token",
    # "examples/update-metadata",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/levicook/arch-token-metadata"

[workspace.dependencies]
# Arch dependencies
apl-token = { git = "ssh://git@github.com/levicook/arch-network.git", default-features = false, package = "apl-token" }
arch_program = { git = "ssh://git@github.com/levicook/arch-network.git", package = "arch_program" }
arch_sdk = { git = "ssh://git@github.com/levicook/arch-network.git", package = "arch_sdk" }
arch_testing = { git = "ssh://git@github.com/levicook/arch-testing.git", default-features = false }
arch_token_metadata = { path = "programs/arch-token-metadata" }

# External dependencies
anyhow = "1"
borsh = "1.5"
bitcoin = "0.32"
num-derive = "0.4"
num-traits = "0.2"
serial_test = "3.2"
thiserror = "2"
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
