[toolchain]

channel = "1.84.1" # exact match for:
# cargo-build-sbf --version
# solana-cargo-build-sbf 2.2.14
# platform-tools v1.48
# rustc 1.84.1 (c7933abbed)
## aka:
# solana --version
# solana-cli 2.2.14 (src:e2b57760; feat:798020478, client:Agave)
## installed via:
# sh -c "$(curl -sSfL https://release.anza.xyz/v2.2.14/install)" 

components = ["rustfmt", "clippy"]

targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]